class BeerData {
  // Helper to inject alphabetical separators into the list
  static List<Map<String, String>> addAlphabeticalSeparators(
    List<Map<String, String>> data,
  ) {
    if (data.isEmpty) return [];

    List<Map<String, String>> result = [];
    String? lastLetter;

    // Keep the first element (the "Select..." hint) if it has an empty value
    if (data.first['value'] == '') {
      result.add(data.first);
    }

    for (var item in data) {
      if (item['value'] == '') continue;

      String currentLabel = item['label'] ?? '';
      if (currentLabel.isNotEmpty) {
        String firstLetter = currentLabel[0].toUpperCase();

        // If the letter changes, insert a separator header
        if (lastLetter != firstLetter) {
          result.add({
            'label': '-- $firstLetter --',
            'value':
                'SEPARATOR_$firstLetter',
          });
          lastLetter = firstLetter;
        }
        result.add(item);
      }
    }
    return result;
  }

  // Array of beer types with labels and identification values
  static const List<Map<String, String>> beerTypes = [
    {'label': 'Sélectionner le type', 'value': ''},
    {'label': 'Ambrée', 'value': 'Ambrée'},
    {'label': 'Amber Ale', 'value': 'Amber Ale'},
    {'label': 'American Barleywine', 'value': 'American Barleywine'},
    {'label': 'American Pale Ale (APA)', 'value': 'APA'},
    {'label': 'American Wheat Ale', 'value': 'American Wheat Ale'},
    {'label': 'Blonde', 'value': 'Blonde'},
    {'label': 'Blanche', 'value': 'Blanche'},
    {'label': 'Blanche IPA', 'value': 'Blanche IPA'},
    {'label': 'Brown Ale', 'value': 'Brown Ale'},
    {'label': 'Barleywine', 'value': 'Barleywine'},
    {'label': 'Berliner Weisse', 'value': 'Berliner Weisse'},
    {'label': 'Berliner Sour', 'value': 'Berliner Sour'},
    {'label': 'Baltic Porter', 'value': 'Baltic Porter'},
    {'label': 'Brune', 'value': 'Brune'},
    {'label': 'California Common', 'value': 'California Common'},
    {'label': 'Cream Ale', 'value': 'Cream Ale'},
    {'label': 'Double IPA (DIPA)', 'value': 'DIPA'},
    {'label': 'DDH IPA', 'value': 'DDH IPA'},
    {'label': 'DDH DIPA', 'value': 'DDH DIPA'},
    {'label': 'DDH TIPA', 'value': 'DDH TIPA'},
    {'label': 'DDH NEIPA', 'value': 'DDH NEIPA'},
    {'label': 'DDH Pale Ale', 'value': 'DDH Pale Ale'},
    {'label': 'DDH Hazy IPA', 'value': 'DDH Hazy IPA'},
    {'label': 'DDH West Coast IPA', 'value': 'DDH West Coast IPA'},
    {'label': 'DDH Session IPA', 'value': 'DDH Session IPA'},
    {'label': 'English Barleywine', 'value': 'English Barleywine'},
    {'label': 'Flanders Red Ale', 'value': 'Flanders Red Ale'},
    {'label': 'Fruited Sour', 'value': 'Fruited Sour'},
    {'label': 'Gose', 'value': 'Gose'},
    {'label': 'Gueuze', 'value': 'Gueuze'},
    {'label': 'Hazy IPA', 'value': 'Hazy IPA'},
    {'label': 'Hefeweizen', 'value': 'Hefeweizen'},
    {'label': 'Hoppy Lager', 'value': 'Hoppy Lager'},
    {'label': 'India Pale Ale (IPA)', 'value': 'IPA'},
    {'label': 'IPA anglaise', 'value': 'IPA anglaise'},
    {'label': 'IPA belge', 'value': 'IPA belge'},
    {'label': 'IPA noire', 'value': 'IPA noire'},
    {'label': 'Irish Red Ale', 'value': 'Irish Red Ale'},
    {'label': 'Imperial Stout', 'value': 'Imperial Stout'},
    {'label': 'Kristallweizen', 'value': 'Kristallweizen'},
    {'label': 'Kriek', 'value': 'Kriek'},
    {'label': 'Lager', 'value': 'Lager'},
    {'label': 'Lager blonde', 'value': 'Lager blonde'},
    {'label': 'Lager ambrée', 'value': 'Lager ambrée'},
    {'label': 'Lambic', 'value': 'Lambic'},
    {'label': 'Marzen', 'value': 'Marzen'},
    {'label': 'Milk Stout', 'value': 'Milk Stout'},
    {'label': 'New England IPA (NEIPA)', 'value': 'NEIPA'},
    {'label': 'New Zealand IPA', 'value': 'New Zealand IPA'},
    {'label': 'Oatmeal Stout', 'value': 'Oatmeal Stout'},
    {'label': 'Pale Ale', 'value': 'Pale Ale'},
    {'label': 'Pastry Sour', 'value': 'Pastry Sour'},
    {'label': 'Pilsner', 'value': 'Pilsner'},
    {'label': 'Porter', 'value': 'Porter'},
    {'label': 'Quadrupel', 'value': 'Quadrupel'},
    {'label': 'Red IPA', 'value': 'Red IPA'},
    {'label': 'Rousse', 'value': 'Rousse'},
    {'label': 'Saison', 'value': 'Saison'},
    {'label': 'Saison ambrée', 'value': 'Saison ambrée'},
    {'label': 'Saison fruitée', 'value': 'Saison fruitée'},
    {'label': 'Session IPA', 'value': 'Session IPA'},
    {'label': 'Sour', 'value': 'Sour'},
    {'label': 'Sour Ale', 'value': 'Sour Ale'},
    {'label': 'Stout', 'value': 'Stout'},
    {'label': 'Triple', 'value': 'Triple'},
    {'label': 'Tripel', 'value': 'Tripel'},
    {'label': 'Triple IPA (TIPA)', 'value': 'TIPA'},
    {'label': 'TDH IPA', 'value': 'TDH IPA'},
    {'label': 'TDH NEIPA', 'value': 'TDH NEIPA'},
    {'label': 'Triple NEIPA', 'value': 'Triple NEIPA'},
    {'label': 'West Coast IPA', 'value': 'West Coast IPA'},
    {'label': 'Weizenbock', 'value': 'Weizenbock'},
    {'label': 'White IPA', 'value': 'White IPA'},
    {'label': 'Witbier', 'value': 'Witbier'},
  ];

  // List for beer colors
  static const List<Map<String, String>> beerColors = [
    {'label': 'Sélectionner la couleur', 'value': ''},
    {'label': 'Blonde', 'value': 'Blonde'},
    {'label': 'Ambrée', 'value': 'Ambrée'},
    {'label': 'Brune', 'value': 'Brune'},
    {'label': 'Noire', 'value': 'Noire'},
    {'label': 'Rouge', 'value': 'Rouge'},
  ];

  // List of manufacturing countries
  static const List<Map<String, String>> beerManufacturingPlaces = [
    {'label': 'Sélectionner une origine', 'value': ''},
    {'label': 'Allemagne', 'value': 'Allemagne'},
    {'label': 'Belgique', 'value': 'Belgique'},
    {'label': 'Brésil', 'value': 'Brésil'},
    {'label': 'Chine', 'value': 'Chine'},
    {'label': 'Danemark', 'value': 'Danemark'},
    {'label': 'Espagne', 'value': 'Espagne'},
    {'label': 'États-Unis', 'value': 'États-Unis'},
    {'label': 'Finlande', 'value': 'Finlande'},
    {'label': 'France', 'value': 'France'},
    {'label': 'Irlande', 'value': 'Irlande'},
    {'label': 'Italie', 'value': 'Italie'},
    {'label': 'Japon', 'value': 'Japon'},
    {'label': 'Mexique', 'value': 'Mexique'},
    {'label': 'Norvège', 'value': 'Norvège'},
    {'label': 'Pays-Bas', 'value': 'Pays-Bas'},
    {'label': 'Portugal', 'value': 'Portugal'},
    {'label': 'Royaume-Uni', 'value': 'Royaume-Uni'},
    {'label': 'Russie', 'value': 'Russie'},
    {'label': 'Suède', 'value': 'Suède'},
    {'label': 'Suisse', 'value': 'Suisse'},
  ];

  // Keywords used for filtering non-beer related content
  static const List<String> excludedKeywords = [
    "vin",
    "whisky",
    "pain",
    "alimentation",
    "bread",
    "food",
    "spiritueux",
    "liqueur",
    "wine",
    "vodka",
    "cognac",
    "rum",
    "rhum",
    "gin",
    "champagne",
    "soda",
    "jus",
    "alimento",
    "comida",
    "pan",
    "vino",
    "accesorio",
    "Bebida sin alcohol",
    "sin alcohol",
    "sin-alcohol",
    "drink",
    "cola",
    "thé",
    "café",
    "chocolat",
    "liqueurs",
    "apéritif",
    "digestif",
    "cocktail",
    "energy drink",
    "boisson énergisante",
    "jus de fruit",
    "cidre",
    "eau",
    "eau minérale",
    "mineral water",
    "soft drink",
    "non-alcoolisé",
    "non-alcoholic",
    "spirits",
    "tequila",
    "mezcal",
    "martini",
    "vermouth",
    "bridelight",
    "dairie",
    "laiterie",
    "aliment",
    "nutriscore",
    "agriculture",
    "farming",
    "palm oil",
    "palm",
    "oil",
    "huile de palme",
    "huile",
    "palme",
    "0-0",
    "san",
    "tourtel",
    "bordeaux",
    "desalcoolise",
    "rosee",
    "plats préparés",
    "prepared dishes",
    "prêts à manger",
    "ready-to-eat meals",
    "pain",
    "bread",
    "pâtisserie",
    "pastry",
    "boulangerie",
    "bakery",
    "sauces",
    "assaisonnements",
    "seasonings",
    "condiments",
    "épices",
    "spices",
    "herbes",
    "herbs",
    "confiseries",
    "confectionery",
    "sucreries",
    "grains",
    "noix",
    "nuts",
    "graines",
    "seeds",
    "viandes",
    "meats",
    "viande",
    "meat",
    "charcuterie",
    "poulet",
    "chicken",
    "bœuf",
    "beef",
    "porc",
    "pork",
    "agneau",
    "lamb",
    "dinde",
    "turkey",
    "canard",
    "duck",
    "lapin",
    "rabbit",
    "jambon",
    "ham",
    "saucisse",
    "sausage",
    "bacon",
    "lardon",
    "produits laitiers",
    "dairy products",
    "fromagerie",
    "cheese shop",
    "crèmerie",
    "dairy shop",
    "fruits de mer",
    "seafood",
    "poisson",
    "fish",
    "saumon",
    "salmon",
    "thon",
    "tuna",
    "crevette",
    "shrimp",
    "crabe",
    "crab",
    "huître",
    "oyster",
    "moule",
    "mussel",
    "calamar",
    "squid",
    "homard",
    "lobster",
    "lait",
    "milk",
    "fromage",
    "cheese",
    "yaourt",
    "yogurt",
    "beurre",
    "butter",
    "crème",
    "cream",
    "crème glacée",
    "ice cream",
    "carotte",
    "carrot",
    "tomate",
    "tomato",
    "concombre",
    "cucumber",
    "laitue",
    "lettuce",
    "poivron",
    "pepper",
    "chou",
    "cabbage",
    "brocoli",
    "broccoli",
    "épinard",
    "spinach",
    "oignon",
    "onion",
    "ail",
    "garlic",
    "poireau",
    "leek",
    "pomme de terre",
    "potato",
    "haricot",
    "bean",
    "petit pois",
    "pea",
    "maïs",
    "corn",
  ];
}
